Resume Projects/IAB207-main/PhoneApp/auth.py
from flask import Blueprint, session, redirect, url_for, render_template, flash, get_flashed_messages
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user
from .models import User, Auctions
from . import db

bp = Blueprint('auth', __name__, url_prefix='/authentication')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    login_form_instance = LoginForm()
    error = None
    if login_form_instance.validate_on_submit():
        # grab all data from the form
        username = login_form_instance.user_name.data
        pwd = login_form_instance.password.data

        # attempt to grab username from db
        u = User.query.filter_by(name=username).first()
        if u is None:
            error = 'Incorrect username or password'
        # if does exist -> comepare password
        elif not check_password_hash(u.password_hash, pwd):
            error = 'Incorrect password'
        # if password matchs -> login
        if error is None:
            # if error is none -> the username and password are correct
            login_user(u)
            return redirect(url_for('main.index'))
        else:
            flash(error, "danger")

    return render_template('authentication/login.html', form=login_form_instance)


@bp.route('/register', methods=['GET', 'POST'])
def register():
    register_form_instance = RegisterForm()

    if register_form_instance.validate_on_submit():
        # grab all of the data from the form
        username = register_form_instance.user_name.data
        email = register_form_instance.email.data
        pwd = register_form_instance.password.data

        # check if theere is a user with that username already
        # it will return a user object or 'None'
        u = User.query.filter_by(name=username).first()
        if u:
            flash('This username already exists, try different', 'info')
            return redirect(url_for('authentication.login'))

        pwd_hash = generate_password_hash(pwd)
        new_user = User(name=username, emailid=email, password_hash=pwd_hash)

        db.session.add(new_user)
        db.session.commit()
        # if the username is unique we want to create the user and commit to db
        return redirect(url_for('main.index'))

    else:
        return render_template('authentication/register.html', form=register_form_instance)


@bp.route('/logout')
@login_required
def logout():
    logout_user()
    return render_template('authentication/logout.html')

Resume Projects/IAB207-main/PhoneApp/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for
from .models import Model
from flask import Blueprint, render_template, request, session
from PhoneApp.forms import AuctionsForm
from PhoneApp.models import Auctions, Bid, User
from PhoneApp import auctions
from sqlalchemy import func
from datetime import datetime
from . import db

bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    auctions = Auctions.query.filter_by().all()
    bids = Bid.query.filter_by().all()
    users = User.query.filter_by().all()
    full_page = 'Yes'

    # grab attribute of the auction
    for auction in auctions:
        # starting_bid
        starting_bid = (float(auction.open_bid))

        # current_bid
        current_bid = db.session.query(
            func.max(Bid.bid_amount)).filter_by(auction_id=auction.id).scalar()
        # if current is not None format to 2 decimal
        if current_bid is not None:
            auction.current_bid = "${:.2f}".format(current_bid)
        # if there are no bids on this auction show starting bid instead
        else:
            auction.current_bid = "${:.2f}".format(starting_bid)
        # bid number
        auction.bid_number = Bid.query.filter_by(
            auction_id=auction.id).count()
        auction.timeleft = auction.end - datetime.now()

    return render_template('index.html', auctions=auctions, bids=bids, users=users, full_page=full_page)


@bp.route('/search')
def search():
    if request.args['search']:
        bids = Bid.query.filter_by().all()
        users = User.query.filter_by().all()
        auc = "%" + request.args['search'] + '%'
        auctions = Auctions.query.filter(
            Auctions.title.like(auc)).all()
        full_page = 'No'

        # grab attribute of the auction
        for auction in auctions:
            # starting_bid
            starting_bid = (float(auction.open_bid))

            # current_bid
            current_bid = db.session.query(
                func.max(Bid.bid_amount)).filter_by(auction_id=auction.id).scalar()
            # if current is not None format to 2 decimal
            if current_bid is not None:
                auction.current_bid = "${:.2f}".format(current_bid)
            # if there are no bids on this auction show starting bid instead
            else:
                auction.current_bid = "${:.2f}".format(starting_bid)
            # bid number
            auction.bid_number = Bid.query.filter_by(
                auction_id=auction.id).count()
            auction.timeleft = auction.end-datetime.now()

        return render_template('index.html', auctions=auctions, bids=bids, users=users, full_page=full_page)
    else:
        return redirect(url_for('main.index'))

Resume Projects/IAB207-main/PhoneApp/templates/base.html
<html>

<head>

  <!-- Title of the app-->

  <title>TechDrop</title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>

  <!-- Header -->

  <header class="bg-light border-bottom">

    <!-- Navbar -->
    <!-- currently does nothing but is for navbar colours coords-->
    <style>
      .navbar-custom .navbar-brand,
      .navbar-custom .navbar-text {
        color: #05386B;
      }

      .navbar-custom {
        float: left;
        text-align: center;
        padding: 12px;
        color: white;
        text-decoration: none;
        font-size: 17px;
      }

      .navbar-buttons {
        margin-left: 70px;
      }

      .navbar-brand {
        margin-left: 30px;
      }



      #ProfileDropdown {
        margin-right: 35px;
        float: right;
        display: flex;
      }

      #searchbar {
        display: inline-block;
      }

      #submitbutton {
        float: right;
      }

      #input {
        width: 300px;
      }

      #userdropdown {
        margin-right: 0px;
        right: 0px;
      }

      #navbarNavDropdown {
        margin-left: 20px;
      }
    </style>



    <nav class="navbar sticky-top navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-music-player" fill="currentColor"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M12 1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z" />
          <path fill-rule="evenodd"
            d="M11 3H5v3h6V3zM5 2a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H5zm3 11a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0z" />
          <circle cx="8" cy="11" r="1" />
        </svg>
        TechDrop
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2" id="navbarNavDropdown">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">
              <path
                d="M6.5 10.995V14.5a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .146-.354l6-6a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 .146.354v7a.5.5 0 0 1-.5.5h-4a.5.5 0 0 1-.5-.5V11c0-.25-.25-.5-.5-.5H7c-.25 0-.5.25-.5.495z" />
              <path fill-rule="evenodd" d="M13 2.5V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
              </svg> Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" {% if current_user.is_authenticated %}
              href="{{url_for('watchlist.watchlist',id=current_user.id)}}" {% else %}
              href="{{url_for('watchlist.watchlist',id=1)}}" {% endif %}>
              <path fill-rule="evenodd"
                d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z" />
              <path fill-rule="evenodd"
                d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z" />
              </svg>
              WatchList</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenu" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <path fill-rule="evenodd"
                d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
              <path fill-rule="evenodd"
                d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
              </svg>
              Search by category
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">New</a>
              <a class="dropdown-item" href="#">Used</a>
              <a class="dropdown-item" href="#">Opened - Never Used</a>
              <a class="dropdown-item" href="#">Seller Refurbished</a>
              <a class="dropdown-item" href="#">Manufacturer Refurbished</a>
              <a class="dropdown-item" href="#">Not Working - For Parts</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">All Phone Brands</a>
            </div>
          </li>
      </div>
      <div class="container mx-auto order-0">
        <form class="form-inline my-2 my-lg-0" id="searchbar" action="{{url_for('main.search')}}">
          <input class="form-control mr-sm-2" type="text" name="search" placeholder="Discover The Best Auctioned Phones"
            aria-label="Search" id="input">
          <button class="btn btn-primary my-2 my-sm-0" type="submit" id="submitbutton">Search</button>
        </form>
      </div>
      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="ProfileDropdown">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            {% if current_user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img class="img-fluid" height="10" width="30"
                src="https://www.flaticon.com/svg/static/icons/svg/1319/1319240.svg">
              {{current_user.name}}

            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="userdropdown">
              <a class="dropdown-item" href="{{ url_for('auction.create') }}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor"
                  xmlns="http://www.w3.org/2000/svg">
                  <path
                    d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
                  <path fill-rule="evenodd"
                    d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
                </svg>
                List A Phone
              </a>
              <a class="dropdown-item" href="/auctions/listed/{{current_user.id}}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-collection" fill="currentColor"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M14.5 13.5h-13A.5.5 0 0 1 1 13V6a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5zm-13 1A1.5 1.5 0 0 1 0 13V6a1.5 1.5 0 0 1 1.5-1.5h13A1.5 1.5 0 0 1 16 6v7a1.5 1.5 0 0 1-1.5 1.5h-13zM2 3a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 0-1h-11A.5.5 0 0 0 2 3zm2-2a.5.5 0 0 0 .5.5h7a.5.5 0 0 0 0-1h-7A.5.5 0 0 0 4 1z" />
                </svg>
                Listed phones
              </a>
              <a class="dropdown-item" href="{{ url_for('auth.logout') }}"
                style="position:relative; left: 5px; top:0px;">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-door-open-fill" fill="currentColor"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M1.5 15a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2.5A1.5 1.5 0 0 0 11.5 1H11V.5a.5.5 0 0 0-.57-.495l-7 1A.5.5 0 0 0 3 1.5V15H1.5zM11 2v13h1V2.5a.5.5 0 0 0-.5-.5H11zm-2.5 8c-.276 0-.5-.448-.5-1s.224-1 .5-1 .5.448.5 1-.224 1-.5 1z" />
                </svg>
                Log Out</a>

            </div>
            {% else %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <svg width="1.7em" height="1.7em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path
                  d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z" />
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z" />
              </svg> Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" id="userdropdown">
              <a class="dropdown-item" href="{{ url_for('auth.login') }}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-door-closed-fill" fill="currentColor"
                  xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd"
                    d="M4 1a1 1 0 0 0-1 1v13H1.5a.5.5 0 0 0 0 1h13a.5.5 0 0 0 0-1H13V2a1 1 0 0 0-1-1H4zm2 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                </svg>

                Log In</a>
              <a class="dropdown-item" href="{{ url_for('auth.register') }}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-signpost-2-fill" fill="currentColor"
                  xmlns="http://www.w3.org/2000/svg">
                  <path d="M7 1.414V16h2V1.414a1 1 0 0 0-2 0z" />
                  <path
                    d="M1 3a1 1 0 0 1 1-1h11.5a1 1 0 0 1 .8.4l.975 1.3a.5.5 0 0 1 0 .6L14.3 5.6a1 1 0 0 1-.8.4H2a1 1 0 0 1-1-1V3zm14 5a1 1 0 0 0-1-1H2.5a1 1 0 0 0-.8.4L.725 8.7a.5.5 0 0 0 0 .6l.975 1.3a1 1 0 0 0 .8.4H14a1 1 0 0 0 1-1V8z" />
                </svg>
                Register</a>
            </div>
            {% endif %}
        </ul>
      </div>
    </nav>


    {% block header%}
    {% endblock %}

  </header>

  {% block content %}
  {% endblock %}

  <footer class="footer">

    <div class="text-center py-2 bg-light" style="position:relative; left: 10px; top:300px;">

      <span class="text-dark">TechDrop Copyright &copy; 2020</span>

    </div>

  </footer>



  <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>





</body>

</html>

Resume Projects/IAB207-main/PhoneApp/templates/user.html
{% include "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block body %}

<div class="page-header">
    <h4>{{heading}}</h4>
</div>



<div class="container-fluid">
{% with messages = get_flashed_messages() %}
{% if messages %}
    {% for message in get_flashed_messages() %}
    <div class ="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-label="close">x</button>
        {{message}}
    </div>
    {% endfor %}
{% endif %}
{% endwith %}

</div>



<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6">
{{wtf.quick_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4">
    <p>New user? <a href="{{ url_for('register') }}">Click here to register</a>.</p>
</div>
{% endif %}

{% endblock %}